### ISSUE TITLE
Улучшить страницу преподавателя

### ISSUE THREAD

**Issue by dyakovri** [profcomff/timetable-backend#21]
Нужно добавить фото преподов, описания и комментарии

## Фото
- Фото препода добавляется ручкой POST `/timetable/lecturer/{id}/photo`, присылается файлом, должно быть ограничение на размер файла (до 3МБ) и фотки должны складываться в папку со статическими файлами
- Папку с фотками захостить в `/photo/lecturer`
- В ручке GET `/timetable/lecturer/{id}` добавить ссылку на файл с фоткой 
- В ручке `/timetable/lecturer` фото отдавать при наличии details=photo

## Описание преподавателя 
- Через POST/PATCH `/timetable/lecturer/{id}` сделать возможноcть добавлять/изменять описание преподавателя
- Описание должно быть в формате markdown, но валидацию лучше не добавлять, пусть на фронтэнде проверка будет при отрисовке
- В ручку GET `/timetable/lecturer/{id}` положить описание
- В ручке GET `/timetable/lecturer` описание отдавать при наличии details=description

## Комментарии к преподавателю
- Создание комментария в ручку POST `/timetable/lecturer/{id}/comment`, принимает имя автора и текст комментария
- Ручки PATCH нет, ручки DELETE и GET (c id и без) работают как обычно. Не забывай пагинацию
- В GET `/timetable/lecturer/{id}` отдавать при наличии `comment_limit != null`, `comment_offset != null`, при comment_limit = 0 отдавать все
- В GET `/timetable/lecturer` комментарии отдавать при наличии details=comments

**Comment by dyakovri** [comment]
Про фотки: со стороны преподавателя сделать ссылку "аватар", со стороны фотки сделать ссылку "препод". На одного препода можно сделать несколько фоток, но только одна из них является аватаркой. Тогда у препода будет 2 relationship: photo (массив фоток) и avatar (одно фото).

В ручке GET `/timetable/lecturer/{id}` добавить ссылку на файл с **аватаркой**. В ручке `/timetable/lecturer`  отдавать при наличии `details=photo` **аватарку**. Все фотки получаются только через ручку GET `/timetable/lecturer/{id}/photo`.

**Comment by dyakovri** [comment]
Как устроить связь между табличками в БД
![image](https://user-images.githubusercontent.com/5656720/185891060-024096b3-77e0-4f91-9ddf-6d5f340103a0.png)

Скорее всего будет проблема с раскаткой внешних ключей, надо будет вручную последовательность создания задавать (здравствуй алембик)

**Comment by dyakovri** [comment]
Когда фотки тебе будут кидать – ты их кладешь в отдельную папку и ставишь название из 32 случайных символов `А-Za-z0-9`. Чтобы парсить их у нас было неповадно (Б–Безопасность)

**Comment by semen603089** [comment]
+комментарии к ивентам
